name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Build
        run: docker build .
        working-directory: ${{ matrix.image }}
