name: publish

on:
  schedule:
    - cron: "0 15 * * *"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Enter directory
        run: cd ${{ matrix.image }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        run: docker build . --tag ghcr.io/cubos/remote-images-${{ matrix.image }}:$(date -u +"%Y-%m-%d-%H-%M-%S")

      - name: Docker Push
        run: docker push ghcr.io/cubos/remote-images-${{ matrix.image }}:$(date -u +"%Y-%m-%d-%H-%M-%S")
